// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlu4sxt71DrjoYQz12t-5F6f4oOnQAmMM',
    appId: '1:730556796653:web:0c536ab79fe3dcfca986e4',
    messagingSenderId: '730556796653',
    projectId: 'skilllink-13b14',
    authDomain: 'skilllink-13b14.firebaseapp.com',
    storageBucket: 'skilllink-13b14.firebasestorage.app',
    measurementId: 'G-G5VTMK01E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUzUFQrK8mY7p40qBqT3Y4cXomYUFd7qg',
    appId: '1:730556796653:android:63ac3f26037ead12a986e4',
    messagingSenderId: '730556796653',
    projectId: 'skilllink-13b14',
    storageBucket: 'skilllink-13b14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp3JzKi-n7cQzUkaSc2qCM1c0v4cGfYtQ',
    appId: '1:730556796653:ios:0075c8408ea84163a986e4',
    messagingSenderId: '730556796653',
    projectId: 'skilllink-13b14',
    storageBucket: 'skilllink-13b14.firebasestorage.app',
    iosBundleId: 'com.example.skilllinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp3JzKi-n7cQzUkaSc2qCM1c0v4cGfYtQ',
    appId: '1:730556796653:ios:0075c8408ea84163a986e4',
    messagingSenderId: '730556796653',
    projectId: 'skilllink-13b14',
    storageBucket: 'skilllink-13b14.firebasestorage.app',
    iosBundleId: 'com.example.skilllinkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlu4sxt71DrjoYQz12t-5F6f4oOnQAmMM',
    appId: '1:730556796653:web:ff9de5141820853aa986e4',
    messagingSenderId: '730556796653',
    projectId: 'skilllink-13b14',
    authDomain: 'skilllink-13b14.firebaseapp.com',
    storageBucket: 'skilllink-13b14.firebasestorage.app',
    measurementId: 'G-W5FWQ7398F',
  );
}
